import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";

const workSan = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "FAQ Accordion Card",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={workSan.className}>
        <main className="flex flex-col items-center min-h-screen bg-light-pink bg-mobile sm:bg-desktop bg-contain bg-top bg-no-repeat ">
          {children}
        </main>
      </body>
    </html>
  );
}
